name: bmin
version: 0.1.0
author: Sheheryar Parvaz <skipper308@hotmail.ca>

dependencies:
  - base
  - containers

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
    - bmin

library:
  source-dirs: src
  exposed-modules:
    - Bool
    - Bool.Term
    - Bool.TermSet
    - Algorithm
    - Algorithm.Impl
    - Algorithm.Boom

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - bmin
      - hspec
      - QuickCheck
